"""empty message

Revision ID: 650e0ec3e6f9
Revises: 9a55993392bd
Create Date: 2023-11-17 16:21:17.981952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650e0ec3e6f9'
down_revision = '9a55993392bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_summaries_bill_id_bills'), 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_summaries_bill_id_bills'), type_='foreignkey')
        batch_op.drop_column('bill_id')

    # ### end Alembic commands ###
